networks:
  serving_prod_net:
    external: true

services:
  serving-api:
    container_name: serving-api
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ../data:/data
      - ../artifacts:/artifacts
    ports:
      - "8080:8080"
    networks:
      - serving_prod_net
